add staff for building RPMs for py2/py3
C2Devel/jsonrpclib pull request #1
Opened 2019-10-04 10:05 UTC by FATruden

2019-10-09 10:13 UTC, odivlad requested changes

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +Release:   test0%{?dist}
Не забудь поправить релизфилд.

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +%global _description\
А `_` для чего?

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +* Mon Sep 30 2019 Croc Cloud Engineering <devel@croc.ru> - 0.4.0-0
0.4.0-1.
Первый релиз должен быть `-1`.
Рассылку, наверное, стоит убрать.

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +BuildRequires:  python2-devel
По идее еще `python2-setuptools` нужно добавить. Ты сборку тестировал локально или в koji тоже?
Этот пакет ни на что не зависит? У него нет `Requires`?

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +Summary: %summary
Лучше выровнять с `BuildRequires:`.

2019-10-09 10:13 UTC, odivlad commented on python-jsonrpclib.spec
> +%package -n python2-%{pkgname}
Между секциями `%package`, `%prep`, `%build`, `%install`, `%clean`, `%files`, `%changelog` сделай, пожалуйста, отступы в 2 строки.

2019-11-21 08:54 UTC, FATruden commented on python-jsonrpclib.spec
> +BuildRequires:  python2-devel
Сборку делел через koji.

2019-11-21 10:32 UTC, FATruden commented on python-jsonrpclib.spec
> +%global _description\
потому что есть встроенная переменная %description. А тут типа для нее содержимое описывается чтобы не дублировать текст.

2019-11-21 22:01 UTC, odivlad approved these changes
Не забудь поправить релизфилд.

2020-01-30 11:10 UTC, Ubun1 requested changes

2020-01-30 11:10 UTC, Ubun1 commented on Makefile
> +.PHONY: build install dist sources srpm clean
просьба удалить лишние таргеты

2020-01-30 11:10 UTC, Ubun1 commented
https://koji.cloud.croc.ru/koji/taskinfo?taskID=1003700 - не смог собрать под 6.6

2020-02-17 13:49 UTC, Ubun1 approved these changes

2020-02-17 13:49 UTC, merged